title: Coderdojo Banbridge
description: Community for CoderDojo Banbridge. Contains useful information about the dojo and links to resources used in our sessions.
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
