title: Coderdojo Banbridge
description: Community for CoderDojo Banbridge. Contains useful information about the dojo and links to resources used in our sessions.
navbar: true
google_analytics: UA-106489965-1
show_downloads: false
theme: jekyll-theme-minimal
twitter_username: coderdojobanb
facebook_username: CoderDojoBanbridge

gems:
  - jekyll-mentions
  - jekyll-sitemap
